import { artDirectionDecisionSchema, type ArtDirectionDecision } from "@/domain/schemas";

// These are mock/sample decisions for the first fixture, not authoritative facts about chrysoberyl.
export const chrysoberylArtDirectionDecisions: ArtDirectionDecision[] = [
  artDirectionDecisionSchema.parse({
    id: "decision-reveal-edge-translucency",
    title: "Reveal edge translucency",
    inputResearchFactIds: ["fact-thin-edge-translucency"],
    selectedVisualGoalIds: ["reveal_translucency"],
    selectedTechniqueIds: ["transmitted_backlight", "macro_90_105mm", "edge_detail", "dark_studio"],
    rejectedTechniqueIds: ["bright_field"],
    reasoning: "Backlighting allows thin areas to transmit light while keeping thicker areas visually solid. Macro framing makes the transition readable.",
    expectedOutcome: "The viewer should understand that the material has partial light transmission without perceiving the whole specimen as transparent.",
    risks: ["Artificial glass-like appearance.", "Excessive glow.", "Loss of natural mineral character."],
    confidence: { level: "needs-review", score: 0.5, rationale: "The input is explicitly mock/sample content and must not be generalized to all specimens." },
    notes: "A production review should confirm that transmission is limited to plausible thin or fractured areas.",
  }),
  artDirectionDecisionSchema.parse({
    id: "decision-reveal-crystal-geometry",
    title: "Reveal crystal geometry",
    inputResearchFactIds: ["fact-specimen-form"],
    selectedVisualGoalIds: ["show_crystal_geometry", "show_specimen_shape"],
    selectedTechniqueIds: ["soft_diffuse_light", "rim_light", "three_quarter_view"],
    rejectedTechniqueIds: ["clamshell_light"],
    reasoning: "Soft diffuse light keeps the major crystal faces readable without dramatic shadow, while a restrained rim and three-quarter view separate the silhouette and communicate depth.",
    expectedOutcome: "The viewer can follow the major planes and irregular outline without mistaking the specimen for a polished or perfectly geometric object.",
    risks: ["Overly cinematic appearance.", "Unrealistic reflections.", "A rim light that creates an artificial halo."],
    confidence: { level: "needs-review", score: 0.5, rationale: "The crystalline-form input is mock/sample content." },
    notes: "The rim remains subordinate to the soft key and is not a decorative style choice.",
  }),
  artDirectionDecisionSchema.parse({
    id: "decision-reveal-surface-structure",
    title: "Reveal surface structure",
    inputResearchFactIds: ["fact-surface-structure"],
    selectedVisualGoalIds: ["reveal_surface_relief", "show_crystal_geometry"],
    selectedTechniqueIds: ["raking_side_light", "macro_90_105mm", "macro_detail", "focus_stack_capture"],
    rejectedTechniqueIds: ["clamshell_light"],
    reasoning: "Low-angle raking light makes striations and facet transitions legible, while macro capture and focus stacking retain detail across the relevant depth.",
    expectedOutcome: "Surface structure reads as natural evidence rather than as invented or exaggerated texture.",
    risks: ["Grazing shadows can exaggerate fracture depth.", "Focus-stack artifacts can invent edges."],
    confidence: { level: "needs-review", score: 0.5, rationale: "The surface-structure input is mock/sample content." },
  }),
  artDirectionDecisionSchema.parse({
    id: "decision-clarify-cluster-relationships",
    title: "Clarify cluster relationships",
    inputResearchFactIds: ["fact-cluster-relationships"],
    selectedVisualGoalIds: ["show_specimen_shape", "show_crystal_geometry"],
    selectedTechniqueIds: ["soft_diffuse_light", "rim_light", "three_quarter_view", "short_telephoto", "museum_specimen"],
    rejectedTechniqueIds: ["extreme_macro"],
    reasoning: "A three-quarter view and gentle separation light allow individual forms and natural contact points to remain distinguishable without isolating the cluster from its overall shape.",
    expectedOutcome: "The viewer can understand the relationship between multiple forms while retaining a believable, non-staged cluster.",
    risks: ["A rim light can create an artificial halo.", "Telephoto compression can hide spatial relationships."],
    confidence: { level: "needs-review", score: 0.5, rationale: "The cluster relationship input is mock/sample content." },
  }),
  artDirectionDecisionSchema.parse({
    id: "decision-preserve-faceted-material-reading",
    title: "Preserve faceted material reading",
    inputResearchFactIds: ["fact-faceted-geometry"],
    selectedVisualGoalIds: ["show_crystal_geometry", "represent_color_accurately", "show_surface_luster"],
    selectedTechniqueIds: ["key_fill_rim", "short_telephoto", "three_quarter_view", "editorial_studio"],
    rejectedTechniqueIds: ["butterfly_light"],
    reasoning: "Controlled broad highlights and an oblique view reveal facets and body color, while restrained separation prevents the study from becoming generic luxury-product imagery.",
    expectedOutcome: "Facet geometry and material color remain readable without implying perfection, commercial value, or unsupported clarity.",
    risks: ["Broad highlights can hide facets.", "Editorial styling can imply commercial value or perfection."],
    confidence: { level: "needs-review", score: 0.5, rationale: "The faceted-material input is mock/sample content." },
  }),
];

// These are mock/sample decisions for the second fixture, not authoritative facts about mookaite.
export const mookaiteArtDirectionDecisions: ArtDirectionDecision[] = [
  artDirectionDecisionSchema.parse({
    id: "decision-mookaite-represent-pattern",
    title: "Represent pattern and zoning",
    inputResearchFactIds: ["fact-mookaite-pattern-zoning"],
    selectedVisualGoalIds: ["show_pattern_or_zoning", "represent_color_accurately"],
    selectedTechniqueIds: ["scientific_neutral", "soft_diffuse_light", "controlled_top_down", "deep_focus"],
    rejectedTechniqueIds: ["hard_directional_light", "shallow_depth_of_field"],
    reasoning: "Even neutral illumination and a controlled top-down view keep the sample pattern readable across the surface without directional shadow or selective focus concealing boundaries.",
    expectedOutcome: "The viewer can compare broad pattern areas and restrained color variation without reading the image as a decorative abstract composition.",
    risks: ["Oversaturated color.", "Decorative abstraction that loses material context.", "Directional shadows hiding pattern boundaries."],
    confidence: { level: "needs-review", score: 0.5, rationale: "The pattern input is mock/sample content." },
    notes: "This is a functional documentation choice, not a prescribed style for all mookaite subjects.",
  }),
  artDirectionDecisionSchema.parse({
    id: "decision-mookaite-show-scale",
    title: "Show collection scale and form",
    inputResearchFactIds: ["fact-mookaite-collection-form"],
    selectedVisualGoalIds: ["show_specimen_shape", "show_scale"],
    selectedTechniqueIds: ["daylight_tabletop", "normal_50mm", "specimen_portrait", "scale_reference"],
    rejectedTechniqueIds: ["extreme_macro"],
    reasoning: "A normal perspective and restrained measured reference make the sample's overall form and size legible without turning a close detail into an ambiguous object.",
    expectedOutcome: "The viewer understands the collection-scale object before interpreting its local pattern.",
    risks: ["A decorative prop may imply incorrect scale.", "A tabletop setup may add unwanted reflected color."],
    confidence: { level: "needs-review", score: 0.5, rationale: "The collection-form input is mock/sample content." },
  }),
  artDirectionDecisionSchema.parse({
    id: "decision-mookaite-show-context",
    title: "Show documentary context",
    inputResearchFactIds: ["fact-mookaite-context"],
    selectedVisualGoalIds: ["show_natural_context", "show_scale"],
    selectedTechniqueIds: ["geological_field", "wide_environmental", "environmental_context"],
    rejectedTechniqueIds: ["dark_studio"],
    reasoning: "A wider environmental composition can show a relationship between the sample and its mock field setting while retaining a readable scale cue.",
    expectedOutcome: "The viewer sees contextual information without confusing the setting for proof of provenance.",
    risks: ["Distracting context.", "Unsupported provenance implication.", "Loss of specimen detail at a wide field of view."],
    confidence: { level: "needs-review", score: 0.5, rationale: "The contextual input is mock/sample content." },
  }),
];
