import "@/domain/knowledge";
import { chrysoberylArtDirectionDecisions, mookaiteArtDirectionDecisions } from "@/domain/decisions";
import { mockChrysoberylTranslucencyAsset } from "@/domain/generation";
import { researchReportSchema, type ResearchReport } from "@/domain/research";
import { projectSchema, type Project, type Shot } from "@/domain/schemas";

const now = "2026-09-15T09:00:00.000Z";
const base = { shotPlanId: "plan-chrysoberyl", generatedAssets: [] };

const chrysoberylResearchReport: ResearchReport = researchReportSchema.parse({
  id: "report-chrysoberyl-sample",
  subjectId: "subject-chrysoberyl",
  summary: "Demonstration-only research report showing how source placeholders, claims, visual properties, opportunities, and risks remain separate from art-direction decisions. It is not authoritative mineral research.",
  sources: [
    { id: "source-mock-catalog-note", title: "Mock specimen observation note", type: "placeholder", url: "https://example.com/mock-specimen-note", citation: "Placeholder citation for architecture demonstration only.", reliability: "not verified", notes: "No scientific or catalog authority is claimed." },
    { id: "source-mock-image-reference", title: "Mock image reference", type: "placeholder", url: "https://example.com/mock-image-reference", citation: "Placeholder visual-reference citation for architecture demonstration only.", reliability: "not verified", notes: "Used only to demonstrate source-to-claim linkage." },
  ],
  claims: [
    { id: "fact-specimen-form", statement: "Mock/sample claim: the specimen has readable prismatic faces and an irregular natural outline.", category: "visual observation", confidence: { level: "needs-review", score: 0.5, rationale: "Demonstration-only claim with placeholder sources." }, sourceIds: ["source-mock-catalog-note"], tags: ["sample", "form"] },
    { id: "fact-cluster-relationships", statement: "Mock/sample claim: multiple crystal forms and contact points are visually meaningful.", category: "visual observation", confidence: { level: "needs-review", score: 0.5, rationale: "Demonstration-only claim with placeholder sources." }, sourceIds: ["source-mock-image-reference"], tags: ["sample", "cluster"] },
    { id: "fact-thin-edge-translucency", statement: "Mock/sample claim: thin or fractured areas may show limited light transmission while the bulk remains visually opaque or translucent.", category: "visual behavior", confidence: { level: "needs-review", score: 0.5, rationale: "Demonstration-only claim with placeholder sources." }, sourceIds: ["source-mock-image-reference"], tags: ["sample", "translucency"] },
    { id: "fact-surface-structure", statement: "Mock/sample claim: face striations, joins, and natural texture are useful visual evidence.", category: "surface observation", confidence: { level: "needs-review", score: 0.5, rationale: "Demonstration-only claim with placeholder sources." }, sourceIds: ["source-mock-catalog-note"], tags: ["sample", "surface"] },
    { id: "fact-faceted-geometry", statement: "Mock/sample claim: cut geometry and body color need to remain distinct from luxury-product styling.", category: "presentation constraint", confidence: { level: "needs-review", score: 0.5, rationale: "Demonstration-only claim with placeholder sources." }, sourceIds: ["source-mock-image-reference"], tags: ["sample", "faceted"] },
  ],
  visualProperties: [
    { id: "property-prismatic-outline", name: "Prismatic outline", description: "Mock/sample visual property derived from the form claim; it describes what should be observable, not how it should be lit.", value: "readable irregular prismatic faces", importance: "high", relatedVisualGoalIds: ["show_specimen_shape", "show_crystal_geometry"] },
    { id: "property-thin-edge-light-behavior", name: "Thin-edge light behavior", description: "Mock/sample property describing limited transmission at relevant edges.", value: "localized partial transmission", importance: "high", relatedVisualGoalIds: ["reveal_translucency"] },
    { id: "property-surface-variation", name: "Surface variation", description: "Mock/sample property describing striations, joins, and texture as possible visible evidence.", value: ["striations", "joins", "natural texture"], importance: "medium", relatedVisualGoalIds: ["reveal_surface_relief", "show_crystal_geometry"] },
  ],
  opportunities: [
    { id: "opportunity-edge-transmission", description: "Mock/sample opportunity: show a transition between a thin transmitting edge and a visually solid bulk.", basedOnClaimIds: ["fact-thin-edge-translucency"], suggestedGoalIds: ["reveal_translucency"] },
    { id: "opportunity-geometry", description: "Mock/sample opportunity: make major faces and an irregular outline easy to follow.", basedOnClaimIds: ["fact-specimen-form", "fact-surface-structure"], suggestedGoalIds: ["show_crystal_geometry", "show_specimen_shape"] },
  ],
  risks: [
    { id: "risk-false-transparency", description: "Mock/sample risk: the entire subject could appear glass-like.", reason: "A local thin-edge property could be overgeneralized by visual treatment.", relatedGoalIds: ["reveal_translucency"], avoidanceNotes: "Keep transmission limited to plausible thin or fractured areas and protect highlights." },
    { id: "risk-exaggerated-relief", description: "Mock/sample risk: shadows may invent or exaggerate surface depth.", reason: "Directional light can make small texture changes appear more extreme.", relatedGoalIds: ["reveal_surface_relief", "show_crystal_geometry"], avoidanceNotes: "Use a restrained contrast level and compare the result with the source claim." },
    { id: "risk-commercial-styling", description: "Mock/sample risk: a factual study may be read as luxury advertising.", reason: "Polished highlights and editorial staging can add unsupported commercial meaning.", relatedGoalIds: ["represent_color_accurately", "show_surface_luster"], avoidanceNotes: "Keep material evidence readable and avoid perfection-oriented styling cues." },
  ],
  overallConfidence: { level: "needs-review", score: 0.5, rationale: "All sources and claims are placeholders for model demonstration." },
});

const mookaiteResearchReport: ResearchReport = researchReportSchema.parse({
  id: "report-mookaite-sample",
  subjectId: "subject-mookaite",
  summary: "Demonstration-only research report for a second subject. Its sources, claims, and visual implications are mock/sample content, not authoritative geological research.",
  sources: [
    { id: "source-mookaite-mock-observation", title: "Mock patterned-sample observation", type: "placeholder", url: "https://example.com/mookaite-mock-observation", citation: "Placeholder citation for architecture demonstration only.", reliability: "not verified", notes: "No geological authority is claimed." },
    { id: "source-mookaite-mock-context", title: "Mock field-context reference", type: "placeholder", url: "https://example.com/mookaite-mock-context", citation: "Placeholder visual-reference citation for architecture demonstration only.", reliability: "not verified", notes: "Used only to demonstrate context reasoning." },
  ],
  claims: [
    { id: "fact-mookaite-pattern-zoning", statement: "Mock/sample claim: broad pattern areas and restrained color variation are visually significant for this sample.", category: "visual observation", confidence: { level: "needs-review", score: 0.5, rationale: "Demonstration-only claim with placeholder sources." }, sourceIds: ["source-mookaite-mock-observation"], tags: ["sample", "pattern", "color"] },
    { id: "fact-mookaite-collection-form", statement: "Mock/sample claim: overall collection-scale form should remain readable alongside local surface variation.", category: "presentation constraint", confidence: { level: "needs-review", score: 0.5, rationale: "Demonstration-only claim with placeholder sources." }, sourceIds: ["source-mookaite-mock-observation"], tags: ["sample", "form", "scale"] },
    { id: "fact-mookaite-context", statement: "Mock/sample claim: a documentary setting can help explain context when it is not mistaken for provenance evidence.", category: "context observation", confidence: { level: "needs-review", score: 0.5, rationale: "Demonstration-only claim with placeholder sources." }, sourceIds: ["source-mookaite-mock-context"], tags: ["sample", "context"] },
  ],
  visualProperties: [
    { id: "property-mookaite-pattern", name: "Broad surface pattern", description: "Mock/sample visual property: pattern boundaries need broad, even coverage rather than dramatic surface modeling.", value: "large readable pattern areas", importance: "high", relatedVisualGoalIds: ["show_pattern_or_zoning", "represent_color_accurately"] },
    { id: "property-mookaite-scale", name: "Collection-scale form", description: "Mock/sample visual property: a complete object and credible size cue are useful alongside close detail.", value: "readable overall form", importance: "high", relatedVisualGoalIds: ["show_specimen_shape", "show_scale"] },
  ],
  opportunities: [
    { id: "opportunity-mookaite-pattern", description: "Mock/sample opportunity: compare pattern areas and color variation without hiding boundaries.", basedOnClaimIds: ["fact-mookaite-pattern-zoning"], suggestedGoalIds: ["show_pattern_or_zoning", "represent_color_accurately"] },
    { id: "opportunity-mookaite-context", description: "Mock/sample opportunity: include a documentary setting with a clear limitation on what it proves.", basedOnClaimIds: ["fact-mookaite-context"], suggestedGoalIds: ["show_natural_context", "show_scale"] },
  ],
  risks: [
    { id: "risk-mookaite-oversaturation", description: "Mock/sample risk: color may appear more saturated than the reference supports.", reason: "Warm illumination or processing can exaggerate color variation.", relatedGoalIds: ["represent_color_accurately", "show_pattern_or_zoning"], avoidanceNotes: "Use neutral, even illumination and avoid color-enhancing treatment." },
    { id: "risk-mookaite-decorative-abstraction", description: "Mock/sample risk: pattern may become a decorative abstract image.", reason: "A tight crop can remove form and scale cues.", relatedGoalIds: ["show_pattern_or_zoning", "show_scale"], avoidanceNotes: "Pair a pattern study with a complete-object or measured scale view." },
    { id: "risk-mookaite-context-overclaim", description: "Mock/sample risk: documentary context may imply unsupported provenance.", reason: "A field-like setting can be read as direct evidence of origin.", relatedGoalIds: ["show_natural_context"], avoidanceNotes: "Label context as sample/mock and avoid presenting it as source evidence." },
  ],
  overallConfidence: { level: "needs-review", score: 0.5, rationale: "All sources and claims are placeholders for model demonstration." },
});

type ShotReasoning = Pick<Shot, "researchFactIds" | "artDirectionDecisionIds" | "visualGoalIds" | "techniqueIds" | "successCriteria" | "risks" | "techniqueOverrides" | "productionNotes"> & { generatedAssets?: Shot["generatedAssets"] };

const shot = (id: string, title: string, purpose: string, shotType: string, lighting: string, composition: string, prompt: string, status: "draft" | "ready" | "review", reasoning: ShotReasoning) => ({
  ...base, id, title, purpose, shotType, lighting, composition, generationPrompt: prompt, status,
  subjectState: "Natural chrysoberyl specimen, preserving believable mineral structure.",
  background: "Quiet neutral studio sweep.", cameraNotes: "Close catalog framing with factual material detail.",
  emphasize: ["crystal geometry", "olive-to-honey color", "natural surface variation"],
  avoid: ["neon green", "perfect glass", "generic luxury jewelry styling"],
  ...reasoning,
});

const mookaiteShot = (id: string, title: string, purpose: string, shotType: string, lighting: string, composition: string, prompt: string, status: "draft" | "ready" | "review", reasoning: ShotReasoning) => ({
  shotPlanId: "plan-mookaite", generatedAssets: [], id, title, purpose, shotType, lighting, composition, generationPrompt: prompt, status,
  subjectState: "Mock/sample mookaite collection object, preserving believable natural variation without making geological claims.",
  background: "Context appropriate to the selected visual problem.", cameraNotes: "Use the selected method to preserve pattern, scale, or context without overclaiming evidence.",
  emphasize: ["broad pattern variation", "collection-scale form", "restrained color"],
  avoid: ["oversaturated color", "decorative abstraction", "unsupported provenance"],
  ...reasoning,
});

export const samotsvetyProject: Project = projectSchema.parse({
  id: "project-samotsvety", name: "Samotsvety", description: "A visual catalog of mineral specimens, built for close observation.", createdAt: now, updatedAt: now,
  exportTargets: [{ id: "export-web", projectId: "project-samotsvety", name: "Catalog web image", format: "WebP", dimensions: "2400 × 3000 px", colorSpace: "sRGB", status: "draft" }],
  subjects: [{
    id: "subject-chrysoberyl", projectId: "project-samotsvety", name: "Chrysoberyl", description: "A hard beryllium aluminium oxide mineral valued for distinct crystal forms and optical presence.", createdAt: now, updatedAt: now,
    research: {
      id: "research-chrysoberyl", subjectId: "subject-chrysoberyl", summary: "Mock/sample reference content for depicting a mineral specimen rather than a generalized green gemstone; it is not authoritative research.", identity: "Chrysoberyl", materialType: "Beryllium aluminium oxide mineral", dominantColors: ["yellow-green", "olive", "honey", "warm brown"], transparency: "Transparent to translucent; often uneven through a natural specimen.", crystalHabit: "Prismatic or tabular, with crisp faces and striations; twinning may occur.", opticalCharacteristics: ["Vitreous luster on clean crystal faces", "Translucent zones glow warmly when backlit", "Subtle color zoning"], structuralCharacteristics: ["Well-defined orthorhombic geometry", "Natural joins and matrix can interrupt clean faces"], visualRisks: ["Avoid saturated emerald-green generic gem imagery.", "Do not make every surface perfectly polished or transparent.", "Avoid glassy, melted crystal forms."], visualFacts: [
        { id: "fact-specimen-form", label: "Sample specimen form", detail: "Mock/sample content: the specimen has readable prismatic faces and an irregular natural outline.", confidence: "needs-review", source: "Mock/sample content — not authoritative research" },
        { id: "fact-cluster-relationships", label: "Sample cluster relationship", detail: "Mock/sample content: multiple crystal forms and contact points are visually meaningful.", confidence: "needs-review", source: "Mock/sample content — not authoritative research" },
        { id: "fact-thin-edge-translucency", label: "Sample thin-edge translucency", detail: "Mock/sample content: thin or fractured areas may show limited light transmission while the bulk remains visually opaque or translucent.", confidence: "needs-review", source: "Mock/sample content — not authoritative research" },
        { id: "fact-surface-structure", label: "Sample surface structure", detail: "Mock/sample content: face striations, joins, and natural texture are useful visual evidence.", confidence: "needs-review", source: "Mock/sample content — not authoritative research" },
        { id: "fact-faceted-geometry", label: "Sample faceted geometry", detail: "Mock/sample content: cut geometry and body color need to remain distinct from luxury-product styling.", confidence: "needs-review", source: "Mock/sample content — not authoritative research" },
      ], createdAt: now, updatedAt: now,
    },
    researchReports: [chrysoberylResearchReport],
    artDirectionDecisions: chrysoberylArtDirectionDecisions,
    shotPlans: [{ id: "plan-chrysoberyl", subjectId: "subject-chrysoberyl", title: "Chrysoberyl catalog study", creativeDirection: "Quiet, precise specimen photography that makes material truth feel collectible.", createdAt: now, updatedAt: now, shots: [
      shot("shot-raw-crystal", "Raw crystal", "Establish the specimen’s natural form and scale.", "hero specimen portrait", "Large soft key from upper left with restrained fill.", "Centered vertical portrait with ample negative space.", "Museum-grade mineral catalog photograph of a single natural chrysoberyl crystal, upright on warm off-white seamless paper, yellow-green to honey tones, crisp prismatic faces and subtle surface striations, soft upper-left studio light, quiet negative space, highly factual material rendering.", "ready", { researchFactIds: ["fact-specimen-form"], artDirectionDecisionIds: ["decision-reveal-crystal-geometry"], visualGoalIds: ["show_specimen_shape", "show_crystal_geometry", "show_scale"], techniqueIds: ["scientific_neutral", "soft_diffuse_light", "specimen_portrait", "three_quarter_view", "normal_50mm", "scale_reference"], successCriteria: ["The full specimen silhouette and major planes are readable.", "A credible scale cue is available without dominating the portrait."], risks: ["A museum-like setup can look commercially isolated.", "A single angle can hide a meaningful face."], techniqueOverrides: [], productionNotes: "Use a restrained scale reference outside the primary hero crop if the export can support it." }),
      shot("shot-aggregate", "Crystal aggregate", "Show how multiple crystals relate in a natural cluster.", "contextual specimen study", "Soft side light with a gentle rim to separate forms.", "Three-quarter view, cluster low and slightly right of center.", "Natural chrysoberyl crystal aggregate photographed as a mineral catalog specimen, multiple intergrown yellow-green and honey prismatic crystals with subtle matrix traces, three-quarter view on a muted stone-gray sweep, soft side light, authentic irregular contact points.", "draft", { researchFactIds: ["fact-cluster-relationships"], artDirectionDecisionIds: ["decision-clarify-cluster-relationships"], visualGoalIds: ["show_specimen_shape", "show_crystal_geometry"], techniqueIds: ["soft_diffuse_light", "rim_light", "three_quarter_view", "short_telephoto", "museum_specimen"], successCriteria: ["Individual forms and natural contact points remain distinguishable.", "Edge separation does not create an artificial halo."], risks: ["Rim light can overstate luster or make the cluster look staged.", "Compression can hide spatial relationships."], techniqueOverrides: [{ techniqueId: "rim_light", notes: "Keep the rim below the intensity of the soft side key." }], productionNotes: "Favor a view that shows at least two distinct crystal orientations." }),
      shot("shot-translucency", "Backlit translucency", "Reveal warmth and uneven translucency inside the material.", "material behavior study", "Diffused backlight with minimal frontal fill.", "Tight horizontal crop with the brightest area offset from center.", "Macro mineral photograph of a natural chrysoberyl crystal’s translucent zone, diffused backlight creating a restrained warm honey and yellow-green internal glow, crisp prismatic edges, visible uneven color zoning, charcoal-to-black background, scientific catalog precision.", "ready", { researchFactIds: ["fact-thin-edge-translucency"], artDirectionDecisionIds: ["decision-reveal-edge-translucency"], visualGoalIds: ["reveal_translucency", "reveal_internal_inclusions"], techniqueIds: ["transmitted_backlight", "macro_90_105mm", "edge_detail", "dark_studio"], successCriteria: ["Light transmission is visible at thin or fractured areas.", "The bulk specimen remains visually opaque or appropriately translucent.", "Edge structure remains readable."], risks: ["Making the entire specimen glass-like.", "Excessive glow.", "Clipping highlights."], techniqueOverrides: [{ techniqueId: "transmitted_backlight", notes: "Flag only thin edges; keep frontal fill minimal.", parameters: { backgroundTone: "charcoal to black", custom: { highlightProtection: true } } }], productionNotes: "This is mock/sample reasoning, not a claim about every chrysoberyl specimen.", generatedAssets: [mockChrysoberylTranslucencyAsset] }),
      shot("shot-structure", "Structural detail", "Document face striations, joins, and natural texture.", "macro structural detail", "Low-angle grazing side light.", "Diagonal facet lines traverse the frame.", "High-magnification macro photograph of chrysoberyl crystal structure: natural prismatic face striations, crisp facet transitions, a small irregular contact edge, olive-honey mineral color, low-angle grazing studio light, restrained neutral gray bokeh.", "review", { researchFactIds: ["fact-surface-structure"], artDirectionDecisionIds: ["decision-reveal-surface-structure"], visualGoalIds: ["reveal_surface_relief", "show_crystal_geometry"], techniqueIds: ["raking_side_light", "macro_90_105mm", "macro_detail", "focus_stack_capture"], successCriteria: ["Striations and facet transitions are distinct.", "Natural contact edges remain believable across the focus depth."], risks: ["Grazing shadows can exaggerate fracture depth.", "Focus-stack artifacts can invent edges."], techniqueOverrides: [{ techniqueId: "raking_side_light", notes: "Use low contrast so texture remains descriptive rather than dramatic." }], productionNotes: "Review the final image for shadow-created texture that is not supported by the source reference." }),
      shot("shot-faceted", "Faceted specimen", "Contrast a cut stone’s clarity with the raw material study.", "cut material portrait", "Controlled broad highlights with soft shadow definition.", "Low three-quarter angle with a modest reflection beneath.", "Refined catalog portrait of a single faceted chrysoberyl specimen on pale warm gray acrylic, yellow-green body color with honey undertones, precise facet geometry and controlled broad studio highlights, mineral-study sensibility rather than luxury jewelry advertising.", "draft", { researchFactIds: ["fact-faceted-geometry"], artDirectionDecisionIds: ["decision-preserve-faceted-material-reading"], visualGoalIds: ["show_crystal_geometry", "represent_color_accurately", "show_surface_luster"], techniqueIds: ["key_fill_rim", "short_telephoto", "three_quarter_view", "editorial_studio"], successCriteria: ["Facet geometry stays readable.", "Body color remains believable under controlled highlights.", "The result reads as a material study rather than luxury advertising."], risks: ["Broad highlights can hide facets.", "Editorial styling can imply commercial value or perfection."], techniqueOverrides: [{ techniqueId: "key_fill_rim", notes: "Keep the rim subtle and use broad, non-clipping highlights." }], productionNotes: "This comparison shot uses mock/sample content and does not establish a mineral fact." }),
    ] }],
  }, {
    id: "subject-mookaite", projectId: "project-samotsvety", name: "Mookaite", description: "A second mock/sample subject used to test whether the same domain pipeline can preserve a different visual strategy.", createdAt: now, updatedAt: now,
    research: {
      id: "research-mookaite", subjectId: "subject-mookaite", summary: "Mock/sample reference content for a second subject; it is not authoritative geological research.", identity: "Mookaite", materialType: "Mock/sample material record", dominantColors: ["warm red", "ochre", "cream"], transparency: "Mock/sample opaque surface behavior.", crystalHabit: "Mock/sample collection-scale irregular form.", opticalCharacteristics: ["Mock/sample restrained surface reflection"], structuralCharacteristics: ["Mock/sample broad pattern areas"], visualRisks: ["Avoid oversaturated color.", "Avoid decorative abstraction without scale.", "Avoid unsupported provenance implications."], visualFacts: [
        { id: "fact-mookaite-pattern-zoning", label: "Sample pattern zoning", detail: "Mock/sample content: broad pattern areas and restrained color variation are visually significant.", confidence: "needs-review", source: "Mock/sample content — not authoritative research" },
        { id: "fact-mookaite-collection-form", label: "Sample collection form", detail: "Mock/sample content: overall form should remain readable alongside surface variation.", confidence: "needs-review", source: "Mock/sample content — not authoritative research" },
        { id: "fact-mookaite-context", label: "Sample documentary context", detail: "Mock/sample content: context may be useful when it is not read as provenance evidence.", confidence: "needs-review", source: "Mock/sample content — not authoritative research" },
      ], createdAt: now, updatedAt: now,
    },
    researchReports: [mookaiteResearchReport],
    artDirectionDecisions: mookaiteArtDirectionDecisions,
    shotPlans: [{ id: "plan-mookaite", subjectId: "subject-mookaite", title: "Mookaite pattern and context study", creativeDirection: "A restrained, observational study that distinguishes broad pattern, collection scale, and documentary context.", createdAt: now, updatedAt: now, shots: [
      mookaiteShot("shot-mookaite-pattern", "Pattern survey", "Compare broad pattern areas and restrained color variation without making an abstract decorative image.", "pattern documentation", "Large soft diffuse light with neutral color control.", "Controlled top-down view with the pattern field filling most of the frame.", "Mock/sample material study of a mookaite collection object, broad red, ochre, and cream pattern areas under neutral diffuse illumination, controlled top-down view, deep readable focus, documentary color rendering, no decorative abstraction.", "ready", { researchFactIds: ["fact-mookaite-pattern-zoning"], artDirectionDecisionIds: ["decision-mookaite-represent-pattern"], visualGoalIds: ["show_pattern_or_zoning", "represent_color_accurately"], techniqueIds: ["scientific_neutral", "soft_diffuse_light", "controlled_top_down", "deep_focus"], successCriteria: ["Pattern boundaries remain readable across the frame.", "Color variation is restrained and not clipped or oversaturated."], risks: ["Warm color cast.", "Pattern appearing as an abstract decorative surface.", "Directional shadows hiding boundaries."], techniqueOverrides: [], productionNotes: "This is mock/sample pattern content, not a geological claim." }),
      mookaiteShot("shot-mookaite-scale", "Collection-scale portrait", "Show the whole collection object with a credible size cue before focusing on local pattern.", "scale and form documentation", "Diffuse daylight-style tabletop light with restrained reflection.", "Normal-perspective specimen portrait with a measured scale reference.", "Mock/sample collection-scale mookaite object on a neutral daylight tabletop, normal perspective, complete irregular form, restrained measured scale reference, even color, no luxury-product styling.", "draft", { researchFactIds: ["fact-mookaite-collection-form"], artDirectionDecisionIds: ["decision-mookaite-show-scale"], visualGoalIds: ["show_specimen_shape", "show_scale"], techniqueIds: ["daylight_tabletop", "normal_50mm", "specimen_portrait", "scale_reference"], successCriteria: ["The complete object remains readable.", "The scale cue is credible and subordinate to the subject."], risks: ["Decorative props implying incorrect scale.", "Tabletop reflections changing perceived color."], techniqueOverrides: [], productionNotes: "Use a standardized reference rather than a lifestyle prop." }),
      mookaiteShot("shot-mookaite-context", "Documentary context", "Place the mock sample in a broad documentary setting without presenting context as provenance proof.", "environmental context study", "Available-looking field light with the subject still readable.", "Wide environmental frame with a modest scale cue and visible surrounding material.", "Mock/sample documentary context image of a mookaite collection object in a broad field-like setting, wide environmental perspective, readable subject scale, restrained natural color, context shown as illustrative rather than provenance evidence.", "review", { researchFactIds: ["fact-mookaite-context"], artDirectionDecisionIds: ["decision-mookaite-show-context"], visualGoalIds: ["show_natural_context", "show_scale"], techniqueIds: ["geological_field", "wide_environmental", "environmental_context"], successCriteria: ["Context supports the subject rather than overwhelming it.", "The image does not imply verified provenance."], risks: ["Distracting surroundings.", "Unsupported provenance implication.", "Subject becoming too small in the frame."], techniqueOverrides: [], productionNotes: "Keep any field-like setting explicitly demonstrative and non-evidentiary." }),
    ] }],
  }],
});
