import "@/domain/knowledge";
import { chrysoberylArtDirectionDecisions } from "@/domain/decisions";
import { projectSchema, type Project, type Shot } from "@/domain/schemas";

const now = "2026-09-15T09:00:00.000Z";
const base = { shotPlanId: "plan-chrysoberyl", generatedAssets: [] };

type ShotReasoning = Pick<Shot, "researchFactIds" | "artDirectionDecisionIds" | "visualGoalIds" | "techniqueIds" | "successCriteria" | "risks" | "techniqueOverrides" | "productionNotes">;

const shot = (id: string, title: string, purpose: string, shotType: string, lighting: string, composition: string, prompt: string, status: "draft" | "ready" | "review", reasoning: ShotReasoning) => ({
  ...base, id, title, purpose, shotType, lighting, composition, generationPrompt: prompt, status,
  subjectState: "Natural chrysoberyl specimen, preserving believable mineral structure.",
  background: "Quiet neutral studio sweep.", cameraNotes: "Close catalog framing with factual material detail.",
  emphasize: ["crystal geometry", "olive-to-honey color", "natural surface variation"],
  avoid: ["neon green", "perfect glass", "generic luxury jewelry styling"],
  ...reasoning,
});

export const samotsvetyProject: Project = projectSchema.parse({
  id: "project-samotsvety", name: "Samotsvety", description: "A visual catalog of mineral specimens, built for close observation.", createdAt: now, updatedAt: now,
  exportTargets: [{ id: "export-web", projectId: "project-samotsvety", name: "Catalog web image", format: "WebP", dimensions: "2400 × 3000 px", colorSpace: "sRGB", status: "draft" }],
  subjects: [{
    id: "subject-chrysoberyl", projectId: "project-samotsvety", name: "Chrysoberyl", description: "A hard beryllium aluminium oxide mineral valued for distinct crystal forms and optical presence.", createdAt: now, updatedAt: now,
    research: {
      id: "research-chrysoberyl", subjectId: "subject-chrysoberyl", summary: "Mock/sample reference content for depicting a mineral specimen rather than a generalized green gemstone; it is not authoritative research.", identity: "Chrysoberyl", materialType: "Beryllium aluminium oxide mineral", dominantColors: ["yellow-green", "olive", "honey", "warm brown"], transparency: "Transparent to translucent; often uneven through a natural specimen.", crystalHabit: "Prismatic or tabular, with crisp faces and striations; twinning may occur.", opticalCharacteristics: ["Vitreous luster on clean crystal faces", "Translucent zones glow warmly when backlit", "Subtle color zoning"], structuralCharacteristics: ["Well-defined orthorhombic geometry", "Natural joins and matrix can interrupt clean faces"], visualRisks: ["Avoid saturated emerald-green generic gem imagery.", "Do not make every surface perfectly polished or transparent.", "Avoid glassy, melted crystal forms."], visualFacts: [
        { id: "fact-specimen-form", label: "Sample specimen form", detail: "Mock/sample content: the specimen has readable prismatic faces and an irregular natural outline.", confidence: "needs-review", source: "Mock/sample content — not authoritative research" },
        { id: "fact-cluster-relationships", label: "Sample cluster relationship", detail: "Mock/sample content: multiple crystal forms and contact points are visually meaningful.", confidence: "needs-review", source: "Mock/sample content — not authoritative research" },
        { id: "fact-thin-edge-translucency", label: "Sample thin-edge translucency", detail: "Mock/sample content: thin or fractured areas may show limited light transmission while the bulk remains visually opaque or translucent.", confidence: "needs-review", source: "Mock/sample content — not authoritative research" },
        { id: "fact-surface-structure", label: "Sample surface structure", detail: "Mock/sample content: face striations, joins, and natural texture are useful visual evidence.", confidence: "needs-review", source: "Mock/sample content — not authoritative research" },
        { id: "fact-faceted-geometry", label: "Sample faceted geometry", detail: "Mock/sample content: cut geometry and body color need to remain distinct from luxury-product styling.", confidence: "needs-review", source: "Mock/sample content — not authoritative research" },
      ], createdAt: now, updatedAt: now,
    },
    artDirectionDecisions: chrysoberylArtDirectionDecisions,
    shotPlans: [{ id: "plan-chrysoberyl", subjectId: "subject-chrysoberyl", title: "Chrysoberyl catalog study", creativeDirection: "Quiet, precise specimen photography that makes material truth feel collectible.", createdAt: now, updatedAt: now, shots: [
      shot("shot-raw-crystal", "Raw crystal", "Establish the specimen’s natural form and scale.", "hero specimen portrait", "Large soft key from upper left with restrained fill.", "Centered vertical portrait with ample negative space.", "Museum-grade mineral catalog photograph of a single natural chrysoberyl crystal, upright on warm off-white seamless paper, yellow-green to honey tones, crisp prismatic faces and subtle surface striations, soft upper-left studio light, quiet negative space, highly factual material rendering.", "ready", { researchFactIds: ["fact-specimen-form"], artDirectionDecisionIds: ["decision-reveal-crystal-geometry"], visualGoalIds: ["show_specimen_shape", "show_crystal_geometry", "show_scale"], techniqueIds: ["scientific_neutral", "soft_diffuse_light", "specimen_portrait", "three_quarter_view", "normal_50mm", "scale_reference"], successCriteria: ["The full specimen silhouette and major planes are readable.", "A credible scale cue is available without dominating the portrait."], risks: ["A museum-like setup can look commercially isolated.", "A single angle can hide a meaningful face."], techniqueOverrides: [], productionNotes: "Use a restrained scale reference outside the primary hero crop if the export can support it." }),
      shot("shot-aggregate", "Crystal aggregate", "Show how multiple crystals relate in a natural cluster.", "contextual specimen study", "Soft side light with a gentle rim to separate forms.", "Three-quarter view, cluster low and slightly right of center.", "Natural chrysoberyl crystal aggregate photographed as a mineral catalog specimen, multiple intergrown yellow-green and honey prismatic crystals with subtle matrix traces, three-quarter view on a muted stone-gray sweep, soft side light, authentic irregular contact points.", "draft", { researchFactIds: ["fact-cluster-relationships"], artDirectionDecisionIds: ["decision-clarify-cluster-relationships"], visualGoalIds: ["show_specimen_shape", "show_crystal_geometry"], techniqueIds: ["soft_diffuse_light", "rim_light", "three_quarter_view", "short_telephoto", "museum_specimen"], successCriteria: ["Individual forms and natural contact points remain distinguishable.", "Edge separation does not create an artificial halo."], risks: ["Rim light can overstate luster or make the cluster look staged.", "Compression can hide spatial relationships."], techniqueOverrides: [{ techniqueId: "rim_light", notes: "Keep the rim below the intensity of the soft side key." }], productionNotes: "Favor a view that shows at least two distinct crystal orientations." }),
      shot("shot-translucency", "Backlit translucency", "Reveal warmth and uneven translucency inside the material.", "material behavior study", "Diffused backlight with minimal frontal fill.", "Tight horizontal crop with the brightest area offset from center.", "Macro mineral photograph of a natural chrysoberyl crystal’s translucent zone, diffused backlight creating a restrained warm honey and yellow-green internal glow, crisp prismatic edges, visible uneven color zoning, charcoal-to-black background, scientific catalog precision.", "ready", { researchFactIds: ["fact-thin-edge-translucency"], artDirectionDecisionIds: ["decision-reveal-edge-translucency"], visualGoalIds: ["reveal_translucency", "reveal_internal_inclusions"], techniqueIds: ["transmitted_backlight", "macro_90_105mm", "edge_detail", "dark_studio"], successCriteria: ["Light transmission is visible at thin or fractured areas.", "The bulk specimen remains visually opaque or appropriately translucent.", "Edge structure remains readable."], risks: ["Making the entire specimen glass-like.", "Excessive glow.", "Clipping highlights."], techniqueOverrides: [{ techniqueId: "transmitted_backlight", notes: "Flag only thin edges; keep frontal fill minimal.", parameters: { backgroundTone: "charcoal to black", custom: { highlightProtection: true } } }], productionNotes: "This is mock/sample reasoning, not a claim about every chrysoberyl specimen." }),
      shot("shot-structure", "Structural detail", "Document face striations, joins, and natural texture.", "macro structural detail", "Low-angle grazing side light.", "Diagonal facet lines traverse the frame.", "High-magnification macro photograph of chrysoberyl crystal structure: natural prismatic face striations, crisp facet transitions, a small irregular contact edge, olive-honey mineral color, low-angle grazing studio light, restrained neutral gray bokeh.", "review", { researchFactIds: ["fact-surface-structure"], artDirectionDecisionIds: ["decision-reveal-surface-structure"], visualGoalIds: ["reveal_surface_relief", "show_crystal_geometry"], techniqueIds: ["raking_side_light", "macro_90_105mm", "macro_detail", "focus_stack_capture"], successCriteria: ["Striations and facet transitions are distinct.", "Natural contact edges remain believable across the focus depth."], risks: ["Grazing shadows can exaggerate fracture depth.", "Focus-stack artifacts can invent edges."], techniqueOverrides: [{ techniqueId: "raking_side_light", notes: "Use low contrast so texture remains descriptive rather than dramatic." }], productionNotes: "Review the final image for shadow-created texture that is not supported by the source reference." }),
      shot("shot-faceted", "Faceted specimen", "Contrast a cut stone’s clarity with the raw material study.", "cut material portrait", "Controlled broad highlights with soft shadow definition.", "Low three-quarter angle with a modest reflection beneath.", "Refined catalog portrait of a single faceted chrysoberyl specimen on pale warm gray acrylic, yellow-green body color with honey undertones, precise facet geometry and controlled broad studio highlights, mineral-study sensibility rather than luxury jewelry advertising.", "draft", { researchFactIds: ["fact-faceted-geometry"], artDirectionDecisionIds: ["decision-preserve-faceted-material-reading"], visualGoalIds: ["show_crystal_geometry", "represent_color_accurately", "show_surface_luster"], techniqueIds: ["key_fill_rim", "short_telephoto", "three_quarter_view", "editorial_studio"], successCriteria: ["Facet geometry stays readable.", "Body color remains believable under controlled highlights.", "The result reads as a material study rather than luxury advertising."], risks: ["Broad highlights can hide facets.", "Editorial styling can imply commercial value or perfection."], techniqueOverrides: [{ techniqueId: "key_fill_rim", notes: "Keep the rim subtle and use broad, non-clipping highlights." }], productionNotes: "This comparison shot uses mock/sample content and does not establish a mineral fact." }),
    ] }],
  }],
});
