import { productionTechniqueSchema, type ProductionTechnique } from "@/domain/schemas";

const composition = (id: string, title: string, description: string, solvesGoals: string[], usefulWhen: string[], avoidWhen: string[], strengths: string[], risks: string[], parameters: Record<string, unknown>, tags: string[]) => productionTechniqueSchema.parse({ id, category: "composition", title, description, solvesGoals, usefulWhen, avoidWhen, strengths, risks, parameters: { custom: {}, ...parameters }, tags });

export const compositionTechniques: ProductionTechnique[] = [
  composition("macro_detail", "Macro detail", "A tight composition centered on one small feature.", ["reveal_surface_relief", "reveal_internal_inclusions"], ["A local feature is more important than whole-object context."], ["Shape or scale needs to be understood from this image alone."], ["Directs attention to fine evidence."], ["Can make scale and location ambiguous."], { cameraAngle: "feature-led close view" }, ["macro", "detail"]),
  composition("specimen_portrait", "Specimen portrait", "An isolated whole-object composition with deliberate orientation.", ["show_specimen_shape", "show_crystal_geometry"], ["The subject needs a primary catalog or reference view."], ["Environmental relationship is the core evidence."], ["Makes silhouette, orientation, and primary form easy to assess."], ["Can become product-like or omit context and scale."], { cameraAngle: "chosen to show primary planes" }, ["object", "catalog"]),
  composition("environmental_context", "Environmental context", "A composition giving surroundings meaningful visual space.", ["show_natural_context", "show_scale"], ["Context changes the interpretation of the subject."], ["Fine details must occupy most of the frame."], ["Shows relationships to place, process, or nearby objects."], ["The subject can become too small or the frame too busy."], { cameraAngle: "subject plus surroundings" }, ["context", "wide"]),
  composition("edge_detail", "Edge detail", "A close composition that keeps a meaningful edge or transition in view.", ["reveal_translucency", "reveal_surface_relief"], ["Thin edges, fractures, or boundary behavior are the evidence."], ["Overall shape must be independently communicated."], ["Supports transmitted light and surface transition studies."], ["Can make a feature look representative of the whole object when it is not."], { cameraAngle: "edge or transition" }, ["edge", "detail"]),
  composition("surface_fill", "Surface fill", "A composition filling most of the frame with a representative surface.", ["show_pattern_or_zoning", "reveal_surface_relief"], ["Distribution across a surface is more informative than silhouette."], ["Scale or object boundaries are essential."], ["Makes pattern and surface variation easy to inspect."], ["Can remove dimensional context and overstate local texture."], { cameraAngle: "near parallel to surface" }, ["surface", "pattern"]),
  composition("controlled_top_down", "Controlled top-down", "A perpendicular or near-perpendicular overhead composition.", ["show_pattern_or_zoning", "show_scale"], ["Plan-view distribution or arranged comparison matters."], ["Side form, depth, or silhouette is the primary evidence."], ["Reduces perspective ambiguity and supports comparison."], ["Can flatten three-dimensional form and produce hidden shadows."], { cameraAngle: "top-down" }, ["top-down", "comparison"]),
  composition("three_quarter_view", "Three-quarter view", "An oblique viewpoint showing front, side, and depth cues.", ["show_specimen_shape", "show_crystal_geometry"], ["A single view should communicate several planes."], ["Exact orthographic comparison is required."], ["Balances silhouette, depth, and surface visibility."], ["Can hide a critical face or introduce perspective bias."], { cameraAngle: "three-quarter" }, ["object", "form"]),
  composition("scale_reference", "Scale reference", "A composition including a restrained, credible size cue.", ["show_scale"], ["Dimensions materially affect interpretation."], ["A scale cue would contaminate a clean hero image."], ["Prevents false assumptions about object size."], ["A familiar object or decorative prop may imply the wrong size."], { custom: { scaleCue: "measured or standardized reference" } }, ["scale", "reference"]),
];
