import { productionTechniqueSchema, type ProductionTechnique } from "@/domain/schemas";

const environment = (id: string, title: string, description: string, solvesGoals: string[], usefulWhen: string[], avoidWhen: string[], strengths: string[], risks: string[], parameters: Record<string, unknown>, tags: string[]) => productionTechniqueSchema.parse({ id, category: "environment", title, description, solvesGoals, usefulWhen, avoidWhen, strengths, risks, parameters: { custom: {}, ...parameters }, tags });

export const environmentTechniques: ProductionTechnique[] = [
  environment("scientific_neutral", "Scientific neutral", "A controlled neutral background and illumination environment for comparison.", ["represent_color_accurately", "show_specimen_shape"], ["Color, shape, or material needs a repeatable baseline."], ["Place, process, or atmosphere is part of the evidence."], ["Minimizes environmental interpretation."], ["May appear clinical, commercially isolated, or lose scale."], { environmentType: "controlled studio", backgroundTone: "neutral" }, ["studio", "documentation"]),
  environment("museum_specimen", "Museum specimen", "A restrained display environment that presents an object as a collected specimen.", ["show_specimen_shape", "show_scale"], ["A catalog or collection context supports interpretation."], ["The subject must be shown in natural context."], ["Provides orderly presentation and optional label or mount cues."], ["Can make a fresh or field subject seem overly curated."], { environmentType: "display", backgroundTone: "muted" }, ["museum", "catalog"]),
  environment("dark_studio", "Dark studio", "A dark controlled setting that supports edge, transmitted, and silhouette lighting.", ["reveal_translucency", "show_surface_luster"], ["Light behavior or silhouette needs separation."], ["Accurate broad color or scale must carry the image alone."], ["Controls spill and makes edge illumination legible."], ["Can look theatrical, hide context, or lose scale."], { environmentType: "controlled studio", backgroundTone: "dark" }, ["studio", "dark"]),
  environment("daylight_tabletop", "Daylight tabletop", "A daylight-led tabletop setup with ordinary material surroundings.", ["represent_color_accurately", "show_scale"], ["A familiar, accessible observational setting is helpful."], ["Strict repeatability or complete lighting control is required."], ["Can provide intuitive scale and natural color cues."], ["Daylight changes, reflected color, and casual props can mislead."], { environmentType: "tabletop", backgroundTone: "natural" }, ["daylight", "tabletop"]),
  environment("macro_laboratory", "Macro laboratory", "A technical close-observation setting with controlled support for magnification.", ["reveal_surface_relief", "reveal_internal_inclusions"], ["Fine detail is the primary evidence."], ["Natural context or a non-technical mood is required."], ["Supports stability, controlled backgrounds, and repeatable detail work."], ["Can imply scientific authority beyond the actual evidence."], { environmentType: "laboratory", custom: { support: "stable close-observation setup" } }, ["macro", "technical"]),
  environment("editorial_studio", "Editorial studio", "A flexible studio environment designed for a deliberate visual narrative.", ["show_specimen_shape", "show_surface_luster"], ["A campaign or editorial purpose permits expressive control."], ["Neutral documentation is the overriding purpose."], ["Supports composition, controlled props, and a coherent visual voice."], ["Can create commercial product appearance or add unsupported meaning."], { environmentType: "editorial studio" }, ["studio", "editorial"]),
  environment("in_situ", "In situ", "The subject shown where it occurs or is used, without removing its setting.", ["show_natural_context", "show_scale"], ["Location and relationship to surroundings are factual evidence."], ["A clean isolated detail is required."], ["Shows context, orientation, and natural scale cues."], ["Distracting context can obscure the subject or imply an unsupported origin."], { environmentType: "natural location" }, ["natural", "documentary"]),
  environment("freshly_excavated", "Freshly excavated", "A field condition immediately after exposure or removal.", ["show_natural_context", "reveal_surface_relief"], ["Fresh surface condition or extraction process matters."], ["A stable, clean catalog baseline is needed."], ["Can show unprocessed condition and material relationships."], ["Loose debris, moisture, and field handling can obscure details."], { environmentType: "field" }, ["field", "process"]),
  environment("rock_outcrop", "Rock outcrop", "A broad geological setting showing material within exposed rock.", ["show_natural_context", "show_scale"], ["Host material and spatial relationship are essential."], ["Small features need isolated close-up evidence."], ["Provides a strong place and formation cue."], ["Complex geology can distract or make the target hard to identify."], { environmentType: "outcrop" }, ["field", "geological"]),
  environment("geological_field", "Geological field", "A documentary field environment for specimen, tools, and landscape relationships.", ["show_natural_context", "show_scale"], ["Field process and surrounding terrain are meaningful."], ["Controlled color or reflection documentation is needed."], ["Connects the subject to observation and collection context."], ["Weather, clutter, and variable light can weaken comparability."], { environmentType: "field" }, ["field", "documentary"]),
  environment("collector_desk", "Collector desk", "A working collection surface with selective handling or archival context.", ["show_scale", "show_specimen_shape"], ["Ownership, comparison, or inspection context is useful."], ["The image must avoid personal or commercial implication."], ["Offers human-scale references and an observational setting."], ["Can become lifestyle content or imply provenance."], { environmentType: "work surface" }, ["collection", "context"]),
  environment("lapidary_workshop", "Lapidary workshop", "A process environment for cutting, polishing, or material preparation.", ["show_natural_context", "show_surface_luster"], ["Making process helps explain the subject state."], ["A raw, unprocessed object must be isolated from process cues."], ["Shows functional tools and transformation context."], ["Tool clutter and commercial associations can distract."], { environmentType: "workshop" }, ["process", "workshop"]),
  environment("wet_after_rain", "Wet after rain", "A naturally or intentionally wet field condition.", ["reveal_surface_relief", "show_pattern_or_zoning"], ["A wet condition itself is the observed subject state."], ["Dry color, luster, or normal appearance must be represented."], ["Can reveal surface contrast and fresh texture."], ["Wet saturation and gloss can misleadingly change perceived color and luster."], { environmentType: "field", custom: { surfaceCondition: "wet" } }, ["field", "wet-condition"]),
];
