import { productionTechniqueSchema, type ProductionTechnique } from "@/domain/schemas";

const lighting = (id: string, title: string, description: string, solvesGoals: string[], usefulWhen: string[], avoidWhen: string[], strengths: string[], risks: string[], parameters: Record<string, unknown>, tags: string[]) => productionTechniqueSchema.parse({ id, category: "lighting", title, description, solvesGoals, usefulWhen, avoidWhen, strengths, risks, parameters: { custom: {}, ...parameters }, tags });

export const lightingTechniques: ProductionTechnique[] = [
  lighting("raking_side_light", "Raking side light", "A low, directional side light that grazes across a surface.", ["reveal_surface_relief", "show_crystal_geometry"], ["Surface relief, fractures, or striations need definition."], ["Color must be documented neutrally or the surface is highly reflective."], ["Makes small changes in surface angle visible."], ["Exaggerated shadows can distort perceived depth and color."], { lightDirection: "low side", lightHardness: "directional" }, ["surface", "directional"]),
  lighting("transmitted_backlight", "Transmitted backlight", "Light placed behind a subject so it passes through translucent areas.", ["reveal_translucency", "reveal_internal_inclusions"], ["Thin edges or internal structure transmit light."], ["The subject is opaque, or transmission would create a false material reading."], ["Separates thin zones and can reveal internal variation."], ["Can falsely suggest transparency, produce excessive glow, or clip highlights."], { lightDirection: "behind subject", lightSize: "diffused", backgroundTone: "dark" }, ["transmission", "internal-structure"]),
  lighting("rim_light", "Rim light", "A rear or side-rear light that outlines an edge.", ["show_specimen_shape", "show_surface_luster"], ["Silhouette separation or edge reflectance matters."], ["The rim would hide surface detail or create a commercial halo."], ["Clarifies outline against a similar background."], ["Can look artificial, clip edges, or overstate luster."], { lightDirection: "rear-side", lightHardness: "controlled" }, ["edge", "separation"]),
  lighting("soft_diffuse_light", "Soft diffuse light", "A broad, soft source that reduces harsh shadow transitions.", ["represent_color_accurately", "show_specimen_shape", "show_pattern_or_zoning"], ["Even color, broad form, or subtle pattern needs to be read."], ["Surface relief or sparkling luster is the main evidence."], ["Produces calm, repeatable documentation."], ["May flatten relief and suppress meaningful highlights."], { lightSize: "large", lightHardness: "soft" }, ["neutral", "documentation"]),
  lighting("hard_directional_light", "Hard directional light", "A small or distant source with crisp shadow edges.", ["reveal_surface_relief", "show_crystal_geometry"], ["Hard edges, planes, or shape transitions need emphasis."], ["Accurate color or subtle low-contrast texture is essential."], ["Defines planes with strong visual separation."], ["Can hide information in shadow and create a dramatic, non-neutral reading."], { lightSize: "small", lightHardness: "hard" }, ["directional", "contrast"]),
  lighting("dark_field", "Dark-field illumination", "Illumination arranged so the field stays dark while scatter or edges become visible.", ["reveal_internal_inclusions", "reveal_translucency"], ["Scattering, edges, or inclusions need separation from a dark field."], ["Overall color or complete object form must be assessed."], ["Can isolate faint internal features."], ["Can create an unfamiliar appearance and hide surrounding form."], { backgroundTone: "dark", custom: { illuminationMode: "dark-field" } }, ["technical", "internal-structure"]),
  lighting("bright_field", "Bright-field illumination", "Even illumination against a bright field for general observation.", ["represent_color_accurately", "show_pattern_or_zoning"], ["Broad color and surface distribution need a familiar baseline."], ["Fine edge scattering is the primary subject."], ["Gives a straightforward, comparable view."], ["Can wash out weak contrast or translucency."], { backgroundTone: "light", lightHardness: "soft" }, ["technical", "baseline"]),
  lighting("cross_polarized_light", "Cross-polarized light", "Polarized illumination and viewing used to control specular reflection.", ["represent_color_accurately", "show_pattern_or_zoning"], ["Glare obscures color, pattern, or surface information."], ["Luster itself is a meaningful visual property."], ["Reduces distracting reflections for documentation."], ["Can remove visually meaningful luster and alter perceived saturation."], { polarization: "cross-polarized" }, ["polarization", "glare-control"]),
  lighting("top_light", "Top light", "A source above the subject that emphasizes its upper planes.", ["show_specimen_shape", "show_pattern_or_zoning"], ["A stable overhead view or top-surface pattern is needed."], ["Deep relief needs side definition."], ["Works well with controlled top-down composition."], ["Can flatten side faces and cast obscuring shadows beneath forms."], { lightDirection: "above", lightHardness: "soft" }, ["overhead"]),
  lighting("key_fill_rim", "Key, fill, and rim", "A controlled three-light recipe balancing form, shadow detail, and separation.", ["show_specimen_shape", "show_surface_luster"], ["A complete, polished object description is needed."], ["Minimal, strictly neutral documentation is required."], ["Offers deliberate control of contrast and silhouette."], ["Can become commercial or obscure which lighting cue carries factual meaning."], { custom: { lightRoles: ["key", "fill", "rim"] } }, ["recipe", "studio"]),
  lighting("split_light", "Split light", "A side key dividing a subject into light and shadow halves.", ["show_specimen_shape"], ["A dramatic directional study is explicitly desired."], ["Balanced factual coverage is required."], ["Makes directional form obvious."], ["Can hide half the subject and imply unnecessary drama."], { lightDirection: "90-degree side", lightHardness: "directional" }, ["portrait-recipe", "low-relevance"]),
  lighting("rembrandt_light", "Rembrandt light", "A key-and-fill portrait recipe with a small lit cheek triangle.", ["show_specimen_shape"], ["A human or character portrait needs dimensional modeling."], ["Documenting non-portrait subjects where neutral coverage matters."], ["Provides recognizable portrait form modeling."], ["Its cultural/style association can overwhelm factual depiction."], { custom: { recipe: "portrait key-fill" } }, ["portrait-recipe", "low-relevance"]),
  lighting("butterfly_light", "Butterfly light", "A frontal high key producing a centered shadow under the nose in portrait use.", ["show_specimen_shape"], ["Symmetrical portrait presentation is desired."], ["Surface relief or natural asymmetry needs documentation."], ["Creates clean frontal modeling."], ["Can flatten non-portrait subjects and read as beauty styling."], { lightDirection: "front-above", lightHardness: "soft" }, ["portrait-recipe", "low-relevance"]),
  lighting("clamshell_light", "Clamshell light", "High frontal key with lower fill, primarily a portrait recipe.", ["show_specimen_shape"], ["Low-shadow portrait rendering is intentional."], ["Texture, relief, or luster needs to remain visible."], ["Reduces facial shadows in portrait work."], ["Can eliminate useful texture and become cosmetic or decorative."], { custom: { lightRoles: ["high-front key", "low-front fill"] } }, ["portrait-recipe", "low-relevance"]),
];
