import { productionTechniqueSchema, type ProductionTechnique } from "@/domain/schemas";

const optics = (id: string, title: string, description: string, solvesGoals: string[], usefulWhen: string[], avoidWhen: string[], strengths: string[], risks: string[], parameters: Record<string, unknown>, tags: string[]) => productionTechniqueSchema.parse({ id, category: "optics", title, description, solvesGoals, usefulWhen, avoidWhen, strengths, risks, parameters: { custom: {}, ...parameters }, tags });

export const opticsTechniques: ProductionTechnique[] = [
  optics("macro_90_105mm", "90–105 mm macro", "A moderate telephoto macro perspective with practical working distance.", ["reveal_surface_relief", "show_crystal_geometry"], ["Small subject details need close, controlled coverage."], ["Broad environmental context is essential."], ["Balances magnification, perspective, and lighting access."], ["Limited depth of field can hide relevant structure."], { focalLengthRange: "90–105 mm", workingDistance: "moderate" }, ["macro", "detail"]),
  optics("normal_50mm", "Normal perspective", "A roughly normal field of view for an unexaggerated object relationship.", ["show_specimen_shape", "show_scale"], ["An object should read with familiar perspective."], ["Fine macro detail or a very wide context is needed."], ["Avoids strong wide-angle or telephoto compression."], ["Can be too ordinary or too close for small detail."], { focalLengthRange: "approximately 50 mm" }, ["normal", "perspective"]),
  optics("short_telephoto", "Short telephoto", "A modest telephoto view that simplifies background and perspective.", ["show_specimen_shape", "show_surface_luster"], ["An object needs separation from a distracting background."], ["Spatial relationships or scale cues must remain obvious."], ["Compresses space gently and gives working distance."], ["Can reduce context and obscure depth relationships."], { focalLengthRange: "70–135 mm" }, ["telephoto", "isolation"]),
  optics("wide_environmental", "Wide environmental", "A broad field of view that includes subject and surroundings.", ["show_natural_context", "show_scale"], ["Place, process, or surroundings explain the subject."], ["Edge geometry or exact proportions need neutral depiction."], ["Connects a subject to context and scale."], ["Can distort near objects and make the subject visually small."], { focalLengthRange: "24–35 mm" }, ["wide", "context"]),
  optics("extreme_macro", "Extreme macro", "High magnification for a small isolated feature.", ["reveal_surface_relief", "reveal_internal_inclusions"], ["Minute evidence cannot be read at ordinary close-up scale."], ["Whole-object shape or scale is needed in the same image."], ["Shows fine structure beyond ordinary viewing."], ["Very shallow depth of field and ambiguous scale can mislead."], { focalLengthRange: "macro magnification above 1:1", depthOfField: "very shallow" }, ["macro", "magnification"]),
  optics("deep_focus", "Deep focus", "Optical settings chosen to keep a large depth range readable.", ["show_specimen_shape", "show_pattern_or_zoning"], ["Multiple planes contribute to the evidence."], ["A selective focus cue is the explicit visual goal."], ["Preserves relationships across depth."], ["Small apertures can reduce image quality or require more light."], { depthOfField: "deep" }, ["focus", "coverage"]),
  optics("shallow_depth_of_field", "Shallow depth of field", "A selective-focus method isolating a narrow plane.", ["reveal_surface_relief"], ["Attention must be focused on one verified plane or feature."], ["Multiple planes need factual comparison."], ["Directs attention and reduces background distraction."], ["Can hide relevant evidence and create false importance."], { depthOfField: "shallow" }, ["focus", "selective"]),
  optics("focus_stacking", "Focus stacking", "Multiple focus positions combined to render a deep subject sharply.", ["reveal_surface_relief", "show_crystal_geometry", "reveal_internal_inclusions"], ["Close subjects require detail across more depth than one capture supports."], ["Movement, changing reflections, or rapid capture prevents alignment."], ["Can make macro structure readable across depth."], ["Misalignment or synthetic-looking sharpness can create artifacts."], { depthOfField: "stacked", custom: { captureCount: "multiple focus positions" } }, ["focus", "computational"]),
  optics("near_orthographic_capture", "Near-orthographic capture", "A distant or long-lens setup minimizing perspective change across a subject.", ["show_crystal_geometry", "show_pattern_or_zoning"], ["Proportions, faces, or mapped variation need low distortion."], ["Depth and dimensionality must be emphasized."], ["Preserves comparable geometry across the frame."], ["Can flatten depth and make a form look diagrammatic."], { focalLengthRange: "long lens or distant camera" }, ["geometry", "low-distortion"]),
];
