import { visualGoalSchema, type VisualGoal } from "@/domain/schemas";

export const visualGoals: VisualGoal[] = [
  ["reveal_surface_relief", "Reveal surface relief", "Make raised, recessed, fractured, or textured surfaces legible.", "Show meaningful surface form rather than flattening it.", ["Surface texture, fracture, or relief carries identifying information."], ["Relief is readable without losing the overall form."], ["Exaggerated shadows can make texture appear deeper than it is."], ["raking_side_light", "hard_directional_light", "macro_detail"], ["soft_diffuse_light"], ["surface", "texture"]],
  ["reveal_translucency", "Reveal translucency", "Show how light passes through thin or translucent areas.", "Document material light transmission without overstating it.", ["Thin edges, translucent zones, or internal light behavior matter."], ["Transmission appears only where physically plausible.", "The bulk retains its appropriate opacity."], ["Glow can make an opaque subject appear glass-like."], ["transmitted_backlight", "dark_studio", "edge_detail"], ["bright_field"], ["material", "light-transmission"]],
  ["represent_color_accurately", "Represent color accurately", "Make color useful for comparison and documentation.", "Avoid lighting or processing that changes perceived color.", ["Color is a factual or selection-relevant property."], ["Dominant hues are believable and repeatable.", "Specular highlights do not conceal the color."], ["Mixed light, strong color casts, and wet surfaces can mislead."], ["scientific_neutral", "soft_diffuse_light", "cross_polarized_light"], ["transmitted_backlight"], ["color", "documentation"]],
  ["reveal_internal_inclusions", "Reveal internal inclusions", "Expose inclusions, layers, or internal structure when visible.", "Make internal features readable without inventing depth.", ["Internal structure is relevant to the subject."], ["Features remain distinct from surface reflections."], ["Reflections or excessive glow can be mistaken for inclusions."], ["transmitted_backlight", "extreme_macro", "dark_field"], ["shallow_depth_of_field"], ["internal-structure"]],
  ["show_specimen_shape", "Show specimen shape", "Communicate the complete silhouette and three-dimensional form.", "Establish the subject as an object, not just a detail.", ["Overall form, proportion, or orientation matters."], ["Edges and major planes are clear.", "The full subject is sufficiently visible."], ["Tight crops and shallow focus can obscure shape."], ["specimen_portrait", "three_quarter_view", "soft_diffuse_light"], ["extreme_macro"], ["form", "catalog"]],
  ["show_crystal_geometry", "Show crystal geometry", "Make ordered planes, facets, and directional structure legible.", "Reveal geometric form without stylizing it into a perfect object.", ["Faces, edges, or symmetry are important."], ["Major planes and transitions can be followed."], ["Over-polished highlights can erase natural interruptions."], ["raking_side_light", "macro_90_105mm", "three_quarter_view"], ["clamshell_light"], ["geometry", "structure"]],
  ["show_surface_luster", "Show surface luster", "Represent the way a surface reflects light.", "Show meaningful reflectance while preserving visible form.", ["Luster distinguishes material or finish."], ["Highlights describe the surface without clipping it."], ["Polarization or diffuse light may remove meaningful luster."], ["rim_light", "key_fill_rim", "short_telephoto"], ["cross_polarized_light"], ["luster", "material"]],
  ["show_pattern_or_zoning", "Show pattern or zoning", "Make color, texture, or structural variation across a subject visible.", "Show distribution and boundaries rather than a generalized average.", ["Pattern, zoning, veining, or variation matters."], ["The pattern is readable across its relevant area."], ["Directional light or shallow focus can hide subtle variation."], ["soft_diffuse_light", "controlled_top_down", "deep_focus"], ["shallow_depth_of_field"], ["pattern", "variation"]],
  ["show_scale", "Show scale", "Provide enough reference to judge size.", "Prevent an isolated image from becoming dimensionally ambiguous.", ["Size affects interpretation or use."], ["A credible scale cue is visible or explicitly supplied."], ["A decorative prop can imply the wrong size."], ["scale_reference", "environmental_context", "normal_50mm"], ["extreme_macro"], ["scale", "context"]],
  ["show_natural_context", "Show natural context", "Place the subject in its relevant surroundings.", "Explain origin, use, or relationship to place.", ["Surroundings contribute factual meaning."], ["Context supports rather than overwhelms the subject."], ["Busy surroundings can distract or imply an unsupported origin."], ["in_situ", "geological_field", "wide_environmental", "environmental_context"], ["dark_studio"], ["context", "documentary"]],
].map(([id, title, description, purpose, applicableWhen, successCriteria, risks, recommendedTechniqueIds, conflictingTechniqueIds, tags]) => visualGoalSchema.parse({ id, title, description, purpose, applicableWhen, successCriteria, risks, recommendedTechniqueIds, conflictingTechniqueIds, tags }));
