import { samotsvetyProject } from "@/domain/mock-data";

const workflow = ["Research", "Art Direction", "Shot Plan", "Generate", "Review", "Export"];
const statusStyle = { draft: "bg-stone-100 text-stone-600", ready: "bg-emerald-50 text-emerald-700", generating: "bg-amber-50 text-amber-700", review: "bg-violet-50 text-violet-700", approved: "bg-sky-50 text-sky-700" };

export default function Home() {
  const subject = samotsvetyProject.subjects[0];
  const research = subject.research!;
  const plan = subject.shotPlans[0];
  return <main className="min-h-screen bg-[#f8f7f4] text-[#262422]"><div className="mx-auto flex min-h-screen max-w-[1600px]">
    <aside className="hidden w-72 shrink-0 border-r border-[#dedbd5] bg-[#f1efeb] p-6 lg:flex lg:flex-col">
      <div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-[#262422] text-lg font-semibold text-[#f6c77b]">A</div><div><p className="text-sm font-semibold">Art Director</p><p className="text-xs text-stone-500">Visual production studio</p></div></div>
      <nav className="mt-12 space-y-7" aria-label="Workspace navigation"><section><p className="mb-3 text-[11px] font-semibold uppercase tracking-[.16em] text-stone-500">Projects</p><div className="flex items-center gap-3 rounded-xl bg-white px-3 py-3 shadow-sm"><span className="grid size-7 place-items-center rounded-md bg-[#ead5b1] text-xs font-bold text-[#72561f]">S</span><span className="text-sm font-medium">Samotsvety</span><span className="ml-auto text-stone-400">⌄</span></div></section><section><div className="mb-3 flex items-center justify-between"><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-stone-500">Subjects</p><button aria-label="Add subject" className="text-lg text-stone-400">+</button></div><div className="flex items-center gap-3 rounded-xl border border-[#d7d2ca] bg-[#e9e5df] px-3 py-3"><span className="size-2 rounded-full bg-[#afb863]" /><span className="text-sm font-medium">Chrysoberyl</span></div></section></nav>
      <div className="mt-auto rounded-xl border border-[#dbd6cf] p-4 text-xs leading-5 text-stone-500"><p className="font-medium text-stone-700">Production workspace</p><p className="mt-1">Research is factual. Direction is deliberate.</p></div>
    </aside>
    <div className="min-w-0 flex-1"><header className="flex items-center justify-between border-b border-[#e1ddd7] bg-[#fbfaf8] px-5 py-4 md:px-9"><div className="flex items-center gap-3 lg:hidden"><span className="grid size-8 place-items-center rounded-lg bg-[#262422] text-sm font-semibold text-[#f6c77b]">A</span><span className="text-sm font-semibold">Art Director</span></div><p className="hidden text-sm text-stone-500 lg:block">Samotsvety <span className="mx-2 text-stone-300">/</span> Chrysoberyl</p><button className="rounded-lg border border-[#d8d3cb] bg-white px-3 py-2 text-sm font-medium shadow-sm">Share workspace</button></header>
      <div className="mx-auto max-w-6xl px-5 py-9 md:px-9 md:py-12"><section className="flex flex-col justify-between gap-6 border-b border-[#dedad3] pb-8 md:flex-row md:items-end"><div><p className="mb-3 text-xs font-semibold uppercase tracking-[.16em] text-[#9a742e]">Subject workspace</p><h1 className="font-serif text-4xl tracking-tight md:text-5xl">{subject.name}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-stone-600">{subject.description}</p></div><p className="rounded-full bg-[#e9e6df] px-3 py-1.5 text-xs font-medium text-stone-600">{plan.shots.length} planned shots</p></section>
        <nav className="mt-7 overflow-x-auto" aria-label="Visual production workflow"><div className="flex min-w-max gap-1 rounded-xl bg-[#ece9e3] p-1.5">{workflow.map((step, index) => <div key={step} className={`flex items-center gap-2 rounded-lg px-3 py-2 text-sm ${step === "Shot Plan" ? "bg-white font-semibold shadow-sm" : "text-stone-500"}`}><span className={`grid size-5 place-items-center rounded-full text-[10px] ${step === "Shot Plan" ? "bg-[#b7873e] text-white" : "bg-[#ded9d1]"}`}>{index + 1}</span>{step}</div>)}</div></nav>
        <section className="mt-9 rounded-2xl border border-[#dfdbd4] bg-white p-5 shadow-sm md:p-7"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-baseline"><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-[#9a742e]">Research summary</p><h2 className="mt-1 font-serif text-2xl">Material reference</h2></div><p className="max-w-lg text-sm leading-6 text-stone-600">{research.summary}</p></div><div className="mt-6 grid gap-5 border-t border-[#eeeae4] pt-6 sm:grid-cols-2 xl:grid-cols-3"><Fact label="Identity / material" value={`${research.identity} · ${research.materialType}`} /><Fact label="Dominant colors" value={research.dominantColors.join(" · ")} /><Fact label="Transparency" value={research.transparency} /><Fact label="Crystal habit" value={research.crystalHabit} /><Fact label="Optical / structural" value={[...research.opticalCharacteristics.slice(0, 2), research.structuralCharacteristics[0]].join(" · ")} /><Fact label="Visual risks" value={research.visualRisks.join(" ")} risk /></div></section>
        <section className="mt-10"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-[#9a742e]">Shot plan</p><h2 className="mt-1 font-serif text-3xl">{plan.title}</h2><p className="mt-2 text-sm text-stone-600">{plan.creativeDirection}</p></div><button className="hidden rounded-lg bg-[#2b2824] px-4 py-2.5 text-sm font-medium text-white sm:block">Add shot</button></div><div className="mt-6 grid gap-4 xl:grid-cols-2">{plan.shots.map((item) => <article key={item.id} className="rounded-2xl border border-[#dfdbd4] bg-white p-5 hover:shadow-md"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-medium text-[#987337]">{item.shotType}</p><h3 className="mt-1 text-lg font-semibold">{item.title}</h3></div><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${statusStyle[item.status]}`}>{item.status}</span></div><p className="mt-3 text-sm leading-6 text-stone-600">{item.purpose}</p><div className="mt-5 grid grid-cols-2 gap-3 text-xs"><Detail label="Lighting" value={item.lighting} /><Detail label="Composition" value={item.composition} /></div><div className="mt-5 rounded-xl bg-[#f5f3ef] p-3.5"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-stone-500">Generation prompt</p><p className="mt-2 line-clamp-3 text-sm leading-5 text-stone-700">{item.generationPrompt}</p></div></article>)}</div></section>
      </div></div>
  </div></main>;
}

function Fact({ label, value, risk = false }: { label: string; value: string; risk?: boolean }) { return <div><p className="text-[11px] font-semibold uppercase tracking-[.12em] text-stone-500">{label}</p><p className={`mt-2 text-sm leading-5 ${risk ? "text-[#8b4a3d]" : "text-stone-700"}`}>{value}</p></div>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><p className="font-semibold uppercase tracking-[.1em] text-stone-400">{label}</p><p className="mt-1 leading-5 text-stone-600">{value}</p></div>; }
